json.id user.id
json.first_name user.first_name
json.last_name user.last_name
json.email user.email
json.image user.image
json.address user.address
json.phone_number user.phone_number
json.imdb_url user.imdb_url
json.resume user.resume
json.current_job_title user.current_job_title
json.user_has_projects user.user_has_projects
